### ISSUE TITLE
Please fix gettio

### ISSUE THREAD

**Issue by clemblanco** [owensgit/BeerPad#3]
When I try to install your Google Analytics plugin http://gitt.io/component/analytics.google using gettio command line `gittio install ti.googleanalytics` it says:

```
[ERROR] analytics.google:ios no distributable available
[ERROR] analytics.google:android no distributable available
```

**Comment by boarnoah** [comment]
@Claymm
I think you're trying to uninstall it from project not install it, try:
gittio install ti.googleanalytics

Also make sure you are running it in your project folder, else it might install somewhere else.

I also had success downloading the zip extracting, placing in modules/iphone/analtyics.google and then editing tiapp.xml to use the correct version of google analtyics (you can do that with the GUI from the TiApp Editor page by clicking the little pencil icon and selecting version). 

EDIT: 
Also noticed that this might not be the definitive version
Matt Tuttle has a Google Analtyics specific repo for this at:
https://github.com/MattTuttle/titanium-google-analytics
But that appears to have been moved over to this:
https://github.com/Sitata/titanium-google-analytics

So I'm guessing that's the recommended version to use, unfortunately that doesn't seem to have a gettio page.

**Comment by clemblanco** [comment]
It's working now. Don't really know why. I've used another plugin http://goo.gl/OAVQLB but thanks anyway.
